export const MESSAGE = {
  EMAIL_ALREADY_EXISTS: "Email already exists",
  EMAIL_NOT_FOUND: "Email not found",
  EMAIL_REQUIRED: "Email is required",
  DATA_NOT_EXISTES: "Data not existes",
  INTERNAL_SERVER_ERROR: "Internal server error",
  INVALID_EMAIL: "Invalid email",
  INVALID_PASSWORD: "Invalid password",
  INVALID_REFRESH_TOKEN: "Invalid refresh token",
  LOGIN_SUCCESS: "Login successful",
  PASSWORD_NOT_MATCH: "Password not match",
  PASSWORD_REQUIRED: "Password is required",
  REFRESH_TOKEN_EXPIRED: "Refresh token expired",
  SOMETHING_WRONG: "Something went wrong",
};